#!/usr/bin/expect -f
spawn ./output/x86_64-unknown-linux-gnu/bin/ot-cli-ftd 1
send "panid 0xface\r\n"
expect "Done"
send "ifconfig up\r\n"
expect "Done"
send "routerselectionjitter 1\r\n"
expect "Done"
send "thread start\r\n"
expect "Done"
sleep 5
send "state\r\n"
expect {
    "leader" { send_user ">>>>>>>>>>>>>>>>>>>>>> Good Leader <<<<<<<<<<<<<<<<<<<<<<<<<<<"}
    timeout { exit 1 }
}
expect "Done"
wait
